In [1]:
from seeq import spy
import pandas as pd

In [2]:
# Log into Seeq Server if you're not using Seeq Data Lab:
spy.login(url='http://localhost:34216', credentials_file='../credentials.key', force=False)

# spy.pull

Retrieves data for the specified items over a given time range.

Once you have searched for signals, conditions or scalars and have a DataFrame with an `ID` column, you can execute `spy.pull` to retrieve data for those items.

Alternatively, you can execute `spy.pull('worksheet_url')` if you want to pull all the items loaded in an Analysis 
worksheet by supplying the URL of the Seeq worksheet. You can copy the value of worksheet_url directly out of your 
browser's address bar without further modification.

## Time interval

You must specify `start` and `end`, which can be any data type or format that is recognized by the Pandas function `pandas.to_datetime()`.

Let's create a DataFrame of signals to retrieve data for:

In [3]:
items = spy.search({
    'Path': 'Example >> Cooling Tower 1 >> Area A',
    'Name': 'Compressor'
})

items

,ID,Path,Asset,Name,Description,Type,Value Unit Of Measure,Datasource Name,Archived
0,4EB9637E-49CC-4200-B5D8-35FBB38266FE,Example >> Cooling Tower 1,Area A,Compressor Stage,NaN,StoredSignal,string,Example Data,False
1,371DCDC4-34BE-415D-A27D-D1E8054F566A,Example >> Cooling Tower 1,Area A,Compressor Power,NaN,StoredSignal,kW,Example Data,False

Now we will retrieve that data for a specified time interval:

In [4]:
spy.pull(items, start='2019-01-01', end='2019-01-07')

,Example >> Cooling Tower 1 >> Area A >> Compressor Stage,Example >> Cooling Tower 1 >> Area A >> Compressor Power
2019-01-01 00:00:00-06:00,OFF,0.002923
2019-01-01 00:15:00-06:00,OFF,0.002923
2019-01-01 00:30:00-06:00,OFF,0.002923
2019-01-01 00:45:00-06:00,OFF,0.002923
2019-01-01 01:00:00-06:00,OFF,0.002923
2019-01-01 01:15:00-06:00,OFF,0.002923
2019-01-01 01:30:00-06:00,OFF,0.002923
2019-01-01 01:45:00-06:00,OFF,0.002923
2019-01-01 02:00:00-06:00,OFF,0.002923
2019-01-01 02:15:00-06:00,OFF,0.002923
2019-01-01 02:30:00-06:00,OFF,0.002923
2019-01-01 02:45:00-06:00,OFF,0.002924
2019-01-01 03:00:00-06:00,OFF,0.002923
2019-01-01 03:15:00-06:00,OFF,0.002923
2019-01-01 03:30:00-06:00,OFF,0.002923
2019-01-01 03:45:00-06:00,OFF,0.003023
2019-01-01 04:00:00-06:00,OFF,0.002923
2019-01-01 04:15:00-06:00,OFF,0.002923
2019-01-01 04:30:00-06:00,OFF,0.002923
2019-01-01 04:45:00-06:00,OFF,0.002924
2019-01-01 05:00:00-06:00,OFF,0.002923
2019-01-01 05:15:00-06:00,OFF,0.003022
2019-01-01 05:30:00-06:00,OFF,0.002923
2019-01-01 05:45:00-06:00,OFF,0.002923
2019-01-01 06:00:00-06:00,OFF,0.002923
2019-01-01 06:15:00-06:00,OFF,0.002971
2019-01-01 06:30:00-06:00,OFF,0.002923
2019-01-01 06:45:00-06:00,OFF,0.002923
2019-01-01 07:00:00-06:00,OFF,0.002923
2019-01-01 07:15:00-06:00,OFF,0.002923
...,...,...
2019-01-06 16:45:00-06:00,STAGE 1,16.824415
2019-01-06 17:00:00-06:00,STAGE 1,16.848487
2019-01-06 17:15:00-06:00,STAGE 1,16.870912
2019-01-06 17:30:00-06:00,STAGE 1,16.829447
2019-01-06 17:45:00-06:00,STAGE 1,17.096314
2019-01-06 18:00:00-06:00,STAGE 1,16.864826
2019-01-06 18:15:00-06:00,STAGE 1,16.832780
2019-01-06 18:30:00-06:00,STAGE 1,16.974631
2019-01-06 18:45:00-06:00,STAGE 1,16.989656
2019-01-06 19:00:00-06:00,STAGE 1,16.827607
2019-01-06 19:15:00-06:00,STAGE 1,16.936118
2019-01-06 19:30:00-06:00,STAGE 1,16.761086
2019-01-06 19:45:00-06:00,STAGE 1,16.738498
2019-01-06 20:00:00-06:00,STAGE 1,16.793242
2019-01-06 20:15:00-06:00,STAGE 1,17.139185
2019-01-06 20:30:00-06:00,STAGE 1,17.240060
2019-01-06 20:45:00-06:00,STAGE 1,16.904778
2019-01-06 21:00:00-06:00,STAGE 1,17.175322
2019-01-06 21:15:00-06:00,STAGE 1,16.976229
2019-01-06 21:30:00-06:00,STAGE 1,17.158205
2019-01-06 21:45:00-06:00,STAGE 1,17.015045
2019-01-06 22:00:00-06:00,STAGE 1,16.971339
2019-01-06 22:15:00-06:00,STAGE 1,16.954946
2019-01-06 22:30:00-06:00,STAGE 1,16.839617
2019-01-06 22:45:00-06:00,STAGE 1,16.972018
2019-01-06 23:00:00-06:00,STAGE 1,14.980935
2019-01-06 23:15:00-06:00,OFF,0.002923
2019-01-06 23:30:00-06:00,OFF,0.002923
2019-01-06 23:45:00-06:00,OFF,0.002923
2019-01-07 00:00:00-06:00,OFF,0.002923

The index of the returned DataFrame is `pd.Timestamp` objects with the timezone that is set for the workstation or server that is running Jupyter. Each signal is in a separate column.

Alternatively, you can request a specific timezone for both the input and output (and they can be different):

In [5]:
spy.pull(items,
         start=pd.Timestamp('2019-01-01', tz='US/Pacific'),
         end=pd.Timestamp('2019-01-07', tz='US/Pacific'),
         tz_convert='US/Eastern')

,Example >> Cooling Tower 1 >> Area A >> Compressor Stage,Example >> Cooling Tower 1 >> Area A >> Compressor Power
2019-01-01 03:00:00-05:00,OFF,0.002923
2019-01-01 03:15:00-05:00,OFF,0.002923
2019-01-01 03:30:00-05:00,OFF,0.002923
2019-01-01 03:45:00-05:00,OFF,0.002924
2019-01-01 04:00:00-05:00,OFF,0.002923
2019-01-01 04:15:00-05:00,OFF,0.002923
2019-01-01 04:30:00-05:00,OFF,0.002923
2019-01-01 04:45:00-05:00,OFF,0.003023
2019-01-01 05:00:00-05:00,OFF,0.002923
2019-01-01 05:15:00-05:00,OFF,0.002923
2019-01-01 05:30:00-05:00,OFF,0.002923
2019-01-01 05:45:00-05:00,OFF,0.002924
2019-01-01 06:00:00-05:00,OFF,0.002923
2019-01-01 06:15:00-05:00,OFF,0.003022
2019-01-01 06:30:00-05:00,OFF,0.002923
2019-01-01 06:45:00-05:00,OFF,0.002923
2019-01-01 07:00:00-05:00,OFF,0.002923
2019-01-01 07:15:00-05:00,OFF,0.002971
2019-01-01 07:30:00-05:00,OFF,0.002923
2019-01-01 07:45:00-05:00,OFF,0.002923
2019-01-01 08:00:00-05:00,OFF,0.002923
2019-01-01 08:15:00-05:00,OFF,0.002923
2019-01-01 08:30:00-05:00,OFF,0.002923
2019-01-01 08:45:00-05:00,OFF,0.002923
2019-01-01 09:00:00-05:00,OFF,0.002923
2019-01-01 09:15:00-05:00,OFF,0.002923
2019-01-01 09:30:00-05:00,OFF,0.002923
2019-01-01 09:45:00-05:00,OFF,0.002923
2019-01-01 10:00:00-05:00,OFF,0.002923
2019-01-01 10:15:00-05:00,OFF,0.002923
...,...,...
2019-01-06 19:45:00-05:00,STAGE 1,16.989656
2019-01-06 20:00:00-05:00,STAGE 1,16.827607
2019-01-06 20:15:00-05:00,STAGE 1,16.936118
2019-01-06 20:30:00-05:00,STAGE 1,16.761086
2019-01-06 20:45:00-05:00,STAGE 1,16.738498
2019-01-06 21:00:00-05:00,STAGE 1,16.793242
2019-01-06 21:15:00-05:00,STAGE 1,17.139185
2019-01-06 21:30:00-05:00,STAGE 1,17.240060
2019-01-06 21:45:00-05:00,STAGE 1,16.904778
2019-01-06 22:00:00-05:00,STAGE 1,17.175322
2019-01-06 22:15:00-05:00,STAGE 1,16.976229
2019-01-06 22:30:00-05:00,STAGE 1,17.158205
2019-01-06 22:45:00-05:00,STAGE 1,17.015045
2019-01-06 23:00:00-05:00,STAGE 1,16.971339
2019-01-06 23:15:00-05:00,STAGE 1,16.954946
2019-01-06 23:30:00-05:00,STAGE 1,16.839617
2019-01-06 23:45:00-05:00,STAGE 1,16.972018
2019-01-07 00:00:00-05:00,STAGE 1,14.980935
2019-01-07 00:15:00-05:00,OFF,0.002923
2019-01-07 00:30:00-05:00,OFF,0.002923
2019-01-07 00:45:00-05:00,OFF,0.002923
2019-01-07 01:00:00-05:00,OFF,0.002923
2019-01-07 01:15:00-05:00,OFF,0.002923
2019-01-07 01:30:00-05:00,OFF,0.002923
2019-01-07 01:45:00-05:00,OFF,0.002923
2019-01-07 02:00:00-05:00,OFF,0.002923
2019-01-07 02:15:00-05:00,OFF,0.002923
2019-01-07 02:30:00-05:00,OFF,0.002923
2019-01-07 02:45:00-05:00,OFF,0.002923
2019-01-07 03:00:00-05:00,OFF,0.002923

If you are pulling items from an Analysis worksheet URL, `start` and `end` are selected  by default from the start 
and end of the Display Range in the Trend view of the worksheet. 

`worksheet_url = 'http://localhost:34216/workbook/<workbookID>/worksheet/<worksheetID>'`

`spy.pull(url)`

However, you can always specify a different `start` or `end` when executing `spy.pull` 

`spy.pull(worksheet_url, start='2019-01-01', end='2019-01-07')`

## Gridding

By default, Seeq Server will interpolate data onto a _grid_ at 15 minute intervals. This is often desirable for computation within matrices, and Seeq goes to great lengths to ensure that interpolation is done correctly.

You can change spacing by specifying a `grid` parameter with units of `s`, `min`, `h` or `d`. For example, `grid=1h` will cause samples to be spaced every hour. For dense data, specifying a larger grid interval can significantly reduce the amount of data transferred to Python, which can reduce time taken to pull data.

Alternatively, specifying `grid='auto'` will automatically estimate a grid value. The grid can be determined in either of two ways:

1. If the column `Estimated Sample Period` exists in the query DataFrame, the grid value will be the median of the 
sample periods in the query DataFrame. Note that in this case the sample period is determined for the specified time 
period issued by `spy.search(estimate_sample_period=dict(Start='<sampling_start_time>', 
End='<sampling_end_time>'))`.
2. If the column `Estimated Sample Period` does not exist in the query DataFrame, the grid will be determined by estimating the sample period of each signal in the query DataFrame for the specified time period with the `start` and `end` parameters and then taking the median of all the sample periods. It is highly recommended to estimate the sample period using `spy.search` first since the time taken to pull data can significantly increase for dense data and queries with a large number of signals. 

All signals in Seeq honor their `Maximum Interpolation` property. If the gap between two adjacent samples is larger than `Maximum Interpolation`, then no interpolation is performed and you may see `NaN` entries in the DataFrame, which indicates that there is no appropriate value for that cell. This concept of `Maximum Interpolation` has both a functional purpose and performance implications. It can prevent a process variable like a temperature reading from "flatlining" inappropriately if no data is collected for a period of time. It is also constrains the amount of data that must be retrieved from a source system in order to interpolate correctly to the edges of a request interval.

Specifying `grid=None` retrieves the data with _raw_ timestamps and no interpolation. On rows where signals don't happen to all have values at a particular timestamp, you will see `NaN` entries.

**NaN vs None**: `spy.pull()` uses `NaN` to represent a _missing value_, consistent with Pandas idioms. `None`, on other hand, represents an _invalid_ value, which in Seeq Workbench will break interpolation if one or more invalid samples are located between two valid samples.

## Column headers

By default, column headers will contain the full path to the item (if it's part of an asset tree) or just the name of the item (if it's not in an asset tree).

You can force the column headers to be populated with a particular property using the `header` argument. In this example, the column header will use just the `Name` property:

In [6]:
spy.pull(items, start='2019-01-01T12:00:00', end='2019-01-01T13:00:00', header='Name')

                          Compressor Stage  Compressor Power
2019-01-01 12:00:00-06:00              OFF          0.004884
2019-01-01 12:15:00-06:00              OFF          0.003116
2019-01-01 12:30:00-06:00              OFF          0.002931
2019-01-01 12:45:00-06:00              OFF          0.002923
2019-01-01 13:00:00-06:00              OFF          0.002923

## Applying a Seeq Formula

You can leverage Seeq's time series calculation engine easily by adding a `calculation` argument to `spy.pull()`. For example, let's say we want calculate an hourly average and represent it as a step-interpolated signal. You can figure out what to put as the `calculation` argument by experimenting in Seeq Workbench and going to the _Item Properties_ pane to look at the formula for a particular calculated item in Seeq. Then you copy and paste that _Formula_ property into your notebook, taking care to use either `$signal`, `$condition` or `$scalar` (as appropriate) for the variable name.

Now when we fetch the data, it will have the formula applied to the output:

In [7]:
signal_with_calc = spy.search({'Name': 'Area A_Temperature', 'Datasource Name': 'Example Data'})

spy.pull(signal_with_calc,
         start='2019-01-01T00:00:00',
         end='2019-01-01T03:00:00',
         calculation='$signal.aggregate(average(), hours(), startKey())',
         grid=None)

                           Area A_Temperature
2019-01-01 00:00:00-06:00           90.890074
2019-01-01 01:00:00-06:00           87.795669
2019-01-01 02:00:00-06:00           86.427809
2019-01-01 03:00:00-06:00           85.490003

## Applying a Seeq Formula Across Assets

If you have an asset tree (say, from OSIsoft Asset Framework), you can apply a calculation across assets as long as those assets have the necessary attributes (signals, conditions or scalars) with identical names.

To get started, it's easiest to create the calculation in Seeq Workbench using a single asset first. You can "swap" to other assets by finding an asset in the Data tab and clicking the "swap" button. In this example, we're going to use spy.push() to create a calculated signal for use later.

In [8]:
area_a_signals = spy.search({
    'Path': 'Example >> Cooling Tower 1 >> Area A'
})

dew_point_calc = spy.push(metadata=pd.DataFrame([{
    'Type': 'Signal',
    'Name': 'Dew Point',
    # From https://iridl.ldeo.columbia.edu/dochelp/QA/Basic/dewpoint.html
    'Formula': "$T - ((100 - $RH.setUnits(''))/5)",
    'Formula Parameters': {
        '$T': area_a_signals[area_a_signals['Name'] == 'Temperature'],
        '$RH': area_a_signals[area_a_signals['Name'] == 'Relative Humidity']
    }
}]))

dew_point_calc

,Formula,Formula Parameters,Name,Type,Datasource Class,Datasource ID,Data ID,ID,Push Result
0,$T - ((100 - $RH.setUnits(''))/5),"[RH=91BBC7DF-EDB7-42F8-A727-CDCBA445C765, T=42...",Dew Point,CalculatedSignal,Seeq Data Lab,Seeq Data Lab,[B99794A6-F6AD-42DE-932F-600CDB4626E1] {Signal...,FC0EAFF1-9FAC-4B07-8DFA-282E95F37CB1,Success

Now you can search for all the assets you want to apply this calculation to, and use the `calculation` argument in `spy.pull()` to retrieve data for the various assets.

In [9]:
all_areas = spy.search({
    'Path': 'Example >> Cooling Tower 1'
}, recursive=False)

spy.pull(all_areas, calculation=dew_point_calc)

,Example >> Cooling Tower 1 >> Area A,Example >> Cooling Tower 1 >> Area B,Example >> Cooling Tower 1 >> Area C,Example >> Cooling Tower 1 >> Area G,Example >> Cooling Tower 1 >> Area H,Example >> Cooling Tower 1 >> Area I,Example >> Cooling Tower 1 >> Area J,Example >> Cooling Tower 1 >> Area K
2020-06-10 14:00:00-05:00,76.534638,55.467091,90.025564,71.976149,69.675254,71.661626,62.345215,70.722838
2020-06-10 14:15:00-05:00,77.020232,56.554106,95.034902,71.801481,69.859475,71.772337,65.327843,70.923320
2020-06-10 14:30:00-05:00,77.408705,56.927078,90.566303,71.956650,68.812840,71.884149,68.661414,71.493817
2020-06-10 14:45:00-05:00,79.605475,56.772754,90.158593,72.271837,69.555759,72.161469,71.380090,71.804027

## Conditions

Conditions capture time intervals of interest as _capsules_, which have a start time and an end time. They will not have an end time if they are _uncertain_ (aka _in progress_), and they may not have a start or end time if it lies outside of the time interval (see below for more information).

In order to illustrate how condition data can be pulled, we must first push a simple condition into Seeq. (Don't worry-- this condition will be scoped to a workbook that only you can see.)

In [10]:
compressor_on_high = spy.push(metadata=pd.DataFrame([{
    'Name': 'Compressor on High',
    'Type': 'Condition',    

    'Formula Parameters': {
        # Note here that we are just using a row from our search results. The SPy module will figure
        # out that it contains an identifier that we can use.
        '$cp': items[items['Name'] == 'Compressor Power']
    },

    # This formula specifies capsules to be created when Compressor Power is above 25 kW
    'Formula': '$cp.valueSearch(isGreaterThan(25kW))'    
}]))

compressor_on_high

,Formula,Formula Parameters,Name,Type,Datasource Class,Datasource ID,Data ID,ID,Push Result
0,$cp.valueSearch(isGreaterThan(25kW)),[cp=371DCDC4-34BE-415D-A27D-D1E8054F566A],Compressor on High,CalculatedCondition,Seeq Data Lab,Seeq Data Lab,[B99794A6-F6AD-42DE-932F-600CDB4626E1] {Condit...,2930D169-DA34-4B63-A78C-1631026173C5,Success

We can now pull data for a particular time period for that condition:

In [11]:
spy.pull(compressor_on_high, start='2019-01-01T04:00:00Z', end='2019-01-09T02:00:00Z')

,Condition,Capsule Start,Capsule End,Capsule Is Uncertain
0,Compressor on High,NaT,2019-01-01 05:01:31.176600146+00:00,False
1,Compressor on High,2019-01-02 00:16:37.331031739+00:00,2019-01-02 05:00:33.238973103+00:00,False
2,Compressor on High,2019-01-03 00:13:18.731947840+00:00,2019-01-03 02:55:03.027869976+00:00,False
3,Compressor on High,2019-01-03 17:28:04.251451273+00:00,2019-01-03 18:21:58.603314005+00:00,False
4,Compressor on High,2019-01-04 17:20:33.782090068+00:00,2019-01-04 18:46:41.571969511+00:00,False
5,Compressor on High,2019-01-05 02:18:11.253715409+00:00,2019-01-05 05:01:23.108876186+00:00,False
6,Compressor on High,2019-01-05 17:20:29.256597642+00:00,2019-01-05 18:43:39.192264349+00:00,False
7,Compressor on High,2019-01-07 17:21:18.826407749+00:00,2019-01-07 18:40:09.983726541+00:00,False
8,Compressor on High,2019-01-09 00:13:55.007784046+00:00,NaT,False

If there were multiple conditions, the `Condition` field would show other conditions further down.

Notice that the first capsule (at index 0) has no start time. That's because it starts outside the supplied time interval. Similarly, the last capsule (at index 8) has no end time because it ends outside the supplied time interval.

`Capsule Is Uncertain` will be `True` for capsules whose exit criteria has not yet been satisfied and may change as a result of new data arriving in the system. In Seeq Workbench, such capsules are "hollowed out" in the Gantt bars at the top of the trend.

If we want to know the start and end time even if they're outside our time interval, we can specify a `calculation` argument that applies the `setMaximumDuration()` function, which allows the Seeq calculation engine to retrieve start/end times.

For example:

In [12]:
spy.pull(compressor_on_high,
         start='2019-01-01T04:00:00Z',
         end='2019-01-09T02:00:00Z',
         calculation='$condition.setMaximumDuration(1d)')

,Condition,Capsule Start,Capsule End,Capsule Is Uncertain
0,Compressor on High,2018-12-31 17:19:18.871250820+00:00,2019-01-01 05:01:31.176600146+00:00,False
1,Compressor on High,2019-01-02 00:16:37.331031739+00:00,2019-01-02 05:00:33.238973103+00:00,False
2,Compressor on High,2019-01-03 00:13:18.731947840+00:00,2019-01-03 02:55:03.027869976+00:00,False
3,Compressor on High,2019-01-03 17:28:04.251451273+00:00,2019-01-03 18:21:58.603314005+00:00,False
4,Compressor on High,2019-01-04 17:20:33.782090068+00:00,2019-01-04 18:46:41.571969511+00:00,False
5,Compressor on High,2019-01-05 02:18:11.253715409+00:00,2019-01-05 05:01:23.108876186+00:00,False
6,Compressor on High,2019-01-05 17:20:29.256597642+00:00,2019-01-05 18:43:39.192264349+00:00,False
7,Compressor on High,2019-01-07 17:21:18.826407749+00:00,2019-01-07 18:40:09.983726541+00:00,False
8,Compressor on High,2019-01-09 00:13:55.007784046+00:00,2019-01-09 04:29:12.815103591+00:00,False

Now the first and last capsules have both starts and ends.

It's important to note that setting the _Maximum Duration_ for a Condition to something high can have major performance implications because the Seeq calculation engine is required to potentially evaluate significant amounts of data before/after the query interval to "find" the start/end of the capsule.

### Conditions as signals

You can also request the condition data to be represented as a signal with a value of `1` if a capsule is present at a particular timestamp or `0` if not. Use `shape='samples'` like so:

In [13]:
spy.pull(compressor_on_high, start='2019-01-01T00:00:00Z', end='2019-01-01T12:00:00Z', shape='samples', grid='1h')

                           Compressor on High
2019-01-01 00:00:00+00:00                   1
2019-01-01 01:00:00+00:00                   1
2019-01-01 02:00:00+00:00                   1
2019-01-01 03:00:00+00:00                   1
2019-01-01 04:00:00+00:00                   1
2019-01-01 05:00:00+00:00                   1
2019-01-01 06:00:00+00:00                   0
2019-01-01 07:00:00+00:00                   0
2019-01-01 08:00:00+00:00                   0
2019-01-01 09:00:00+00:00                   0
2019-01-01 10:00:00+00:00                   0
2019-01-01 11:00:00+00:00                   0
2019-01-01 12:00:00+00:00                   0

### Mixing conditions with signals

If the DataFrame that you pass into the `spy.pull()` function contains a mix of signals and conditions, `shape='samples'` will be automatically applied:

In [14]:
compressor_signal_and_condition = spy.search({
    'Path': 'Example >> Cooling Tower 1 >> Area A',
    'Name': 'Compressor Power',
    'Datasource Name': 'Example Data'
}).append(spy.search({
    'Name': 'Compressor*High',
}), sort=False, ignore_index=True)

spy.pull(compressor_signal_and_condition,
         start='2019-01-01T00:00:00Z', end='2019-01-01T12:00:00Z',
         header='Name', grid='1h')

                           Compressor Power  Compressor on High
2019-01-01 00:00:00+00:00         39.189300                 1.0
2019-01-01 01:00:00+00:00         39.326496                 1.0
2019-01-01 02:00:00+00:00         40.223175                 1.0
2019-01-01 03:00:00+00:00         39.431483                 1.0
2019-01-01 04:00:00+00:00         39.139759                 1.0
2019-01-01 05:00:00+00:00         39.154395                 1.0
2019-01-01 06:00:00+00:00          0.002923                 0.0
2019-01-01 07:00:00+00:00          0.002923                 0.0
2019-01-01 08:00:00+00:00          0.002923                 0.0
2019-01-01 09:00:00+00:00          0.002923                 0.0
2019-01-01 10:00:00+00:00          0.002923                 0.0
2019-01-01 11:00:00+00:00          0.002923                 0.0
2019-01-01 12:00:00+00:00          0.002923                 0.0

You can supply `shape='capsules'` to force the output to capsules. In such a case, the signals within the DataFrame will be aggregated within the interval of each capsule according to a statistic. By default, that statistic is `average`, but you can add a `Statistic` column to the passed-in DataFrame to control which statistic is used. To return multiple statistics for the same signal, add additional signal rows to your DataFrame that only vary by the `Statistic` column. The possible statistic function names you can specify are documented in Seeq Workbench's Formula tool documentation under the heading _Signal Value Statistics_.

Let's try this example:

In [15]:
area_a_compressor_power = spy.search({
    'Path': 'Example >> Cooling Tower 1 >> Area A',
    'Name': 'Compressor Power',
    'Datasource Name': 'Example Data'
}, quiet=True)

compressor_on_high = spy.search({
    'Name': 'Compressor*High',
}, quiet=True).iloc[0]

area_a_compressor_power_max = area_a_compressor_power.iloc[0].copy()
area_a_compressor_power_max['Statistic'] = 'maximum'

area_a_compressor_power_delta = area_a_compressor_power.iloc[0].copy()
area_a_compressor_power_delta['Statistic'] = 'totalized'

conditions_with_stats = pd.DataFrame([
    compressor_on_high,
    area_a_compressor_power_max,
    area_a_compressor_power_delta
]).reset_index(drop=True)

conditions_with_stats

,ID,Name,Description,Type,Value Unit Of Measure,Datasource Name,Archived,Path,Asset,Statistic
0,2930D169-DA34-4B63-A78C-1631026173C5,Compressor on High,NaN,CalculatedCondition,NaN,Seeq Data Lab,False,NaN,NaN,NaN
1,371DCDC4-34BE-415D-A27D-D1E8054F566A,Compressor Power,NaN,StoredSignal,kW,Example Data,False,Example >> Cooling Tower 1,Area A,maximum
2,371DCDC4-34BE-415D-A27D-D1E8054F566A,Compressor Power,NaN,StoredSignal,kW,Example Data,False,Example >> Cooling Tower 1,Area A,totalized

Notice that the `Compressor Power` signal appears twice in this DataFrame but has a different value in the `Statistic` column. If we pull with this DataFrame and the `shape='capsules'` argument, we'll get columns for these aggregates:

In [16]:
pull_results = spy.pull(conditions_with_stats,
                        start='2019-01-01T00:00:00Z', end='2019-01-07T00:00:00Z',
                        shape='capsules', header='Name', grid='1h')

# For brevity, drop uncertainty column
pull_results.drop(columns=['Capsule Is Uncertain'])

,Condition,Capsule Start,Capsule End,Compressor Power (Maximum),Compressor Power (Totalized)
0,Compressor on High,NaT,2019-01-01 05:01:31.176600146+00:00,NaN,NaN
1,Compressor on High,2019-01-02 00:16:37.331031739+00:00,2019-01-02 05:00:33.238973103+00:00,37.337571,621836.085754
2,Compressor on High,2019-01-03 00:13:18.731947840+00:00,2019-01-03 02:55:03.027869976+00:00,38.346637,355158.928285
3,Compressor on High,2019-01-03 17:28:04.251451273+00:00,2019-01-03 18:21:58.603314005+00:00,34.499000,109815.164071
4,Compressor on High,2019-01-04 17:20:33.782090068+00:00,2019-01-04 18:46:41.571969511+00:00,35.749304,181575.891856
5,Compressor on High,2019-01-05 02:18:11.253715409+00:00,2019-01-05 05:01:23.108876186+00:00,39.769103,378094.380825
6,Compressor on High,2019-01-05 17:20:29.256597642+00:00,2019-01-05 18:43:39.192264349+00:00,35.700364,174524.224726

## Scalars

Scalars represent a constant value across all time. Let's push one into Seeq to see how it looks when we retrieve it:

In [17]:
compressor_power_limit = spy.push(metadata=pd.DataFrame([{
    'Name': 'Compressor Power Limit',
    'Type': 'Scalar',    
    'Formula': '50kW'    
}]), errors='raise')

compressor_power_limit

,Formula,Name,Type,Datasource Class,Datasource ID,Data ID,ID,Push Result
0,50kW,Compressor Power Limit,CalculatedScalar,Seeq Data Lab,Seeq Data Lab,[B99794A6-F6AD-42DE-932F-600CDB4626E1] {Scalar...,C34C4119-6808-4888-8849-AC2904E0076C,Success

In [18]:
spy.pull(compressor_power_limit)

   Compressor Power Limit
0                      50